using MyWordlistPage.Model;
using System.Collections.ObjectModel;

namespace MyWordlistPage.Services
{ 
    public class LevelAService : LevelService
    {
       

        public override void LoadData()
        {
            pWords = new ObservableCollection<WordlistProvidedModel>
            {
                new WordlistProvidedModel(){ Word = "Huge", Meaning = "ใหญ่โต", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Tiny", Meaning = "เล็กน้อย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Friendly", Meaning = "เป็นมิตร", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Joyful", Meaning = "เยี่ยมยิ่ง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Kind", Meaning = "ใจดี", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cat", Meaning = "แมว", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Dog", Meaning = "หมา", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Table", Meaning = "โต๊ะ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Chair", Meaning = "เก้าอี้", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Book", Meaning = "หนังสือ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Pen", Meaning = "ปากกา", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Pencil", Meaning = "ดินสอ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Run", Meaning = "วิ่ง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Jump", Meaning = "กระโดด", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Walk", Meaning = "เดิน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Eat", Meaning = "กิน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "And", Meaning = "และ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "But", Meaning = "แต่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Or", Meaning = "หรือ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "So", Meaning = "ดังนั้น", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sleep", Meaning = "นอน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Drink", Meaning = "ดื่ม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Study", Meaning = "เรียน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Pretty", Meaning = "สวย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Happy", Meaning = "มีความสุข", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Big", Meaning = "ใหญ่", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Small", Meaning = "เล็ก", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Good", Meaning = "ดี", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bad", Meaning = "แย่", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fast", Meaning = "เร็ว", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Always", Meaning = "เสมอ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Never", Meaning = "ไม่เคย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Often", Meaning = "บ่อยครั้ง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Rarely", Meaning = "นานครั้ง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sometimes", Meaning = "บางครั้ง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Frequently", Meaning = "บ่อยๆ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Read", Meaning = "อ่าน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Write", Meaning = "เขียน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Listen", Meaning = "ฟัง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Speak", Meaning = "พูด", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cook", Meaning = "ทำอาหาร", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Clean", Meaning = "ทำความสะอาด", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Computer", Meaning = "คอมพิวเตอร์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Phone", Meaning = "โทรศัพท์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Car", Meaning = "รถยนต์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "House", Meaning = "บ้าน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Tree", Meaning = "ต้นไม้", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Seldom", Meaning = "ไม่ค่อย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Well", Meaning = "ดี", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Badly", Meaning = "อย่างแย่", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Angrily", Meaning = "อย่างโกรธ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Happily", Meaning = "อย่างมีความสุข", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Chair", Meaning = "เก้าอี้", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Person", Meaning = "คน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Ball", Meaning = "ลูกบอล", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Glass", Meaning = "แก้ว", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Window", Meaning = "หน้าต่าง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Slow", Meaning = "ช้า", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Strong", Meaning = "แข็งแรง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Weak", Meaning = "อ่อนแอ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cold", Meaning = "เย็น", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hot", Meaning = "ร้อน", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Beautiful", Meaning = "สวยงาม", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Ugly", Meaning = "น่าเกลียด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Tall", Meaning = "สูง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Short", Meaning = "สั้น", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Smart", Meaning = "ฉลาด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Because", Meaning = "เพราะว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "If", Meaning = "ถ้า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "When", Meaning = "เมื่อ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Although", Meaning = "แม้ว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "While", Meaning = "ในขณะที่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Stupid", Meaning = "โง่", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Door", Meaning = "ประตู", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Shirt", Meaning = "เสื้อ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Pants", Meaning = "กางเกง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hat", Meaning = "หมวก", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Shoes", Meaning = "รองเท้า", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Among", Meaning = "ในหมู่", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Across", Meaning = "ข้าม", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Through", Meaning = "ผ่าน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Around", Meaning = "รอบ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "With", Meaning = "กับ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Without", Meaning = "โดยไม่มี", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "By", Meaning = "โดย", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "For", Meaning = "สำหรับ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "From", Meaning = "จาก", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Wash", Meaning = "ล้าง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Play", Meaning = "เล่น", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Work", Meaning = "ทำงาน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Pretty", Meaning = "สวย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Kind", Meaning = "ใจดี", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cruel", Meaning = "โหดร้าย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Brave", Meaning = "กล้าหาญ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Possibly", Meaning = "อย่างเป็นไปได้", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Definitely", Meaning = "อย่างแน่นอน", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Exactly", Meaning = "อย่างถูกต้อง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Safely", Meaning = "อย่างปลอดภัย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Dangerously", Meaning = "อย่างอันตราย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Coward", Meaning = "ขี้ขลาด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Happy", Meaning = "มีความสุข", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sad", Meaning = "เศร้า", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Loud", Meaning = "ดัง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Quiet", Meaning = "เงียบ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Old", Meaning = "เก่า", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "New", Meaning = "ใหม่", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sing", Meaning = "ร้องเพลง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Dance", Meaning = "เต้นรำ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Watch", Meaning = "ดู", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Smile", Meaning = "ยิ้ม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cry", Meaning = "ร้องไห้", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Laugh", Meaning = "หัวเราะ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Think", Meaning = "คิด", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Forget", Meaning = "ลืม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Remember", Meaning = "จำได้", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Help", Meaning = "ช่วยเหลือ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hurt", Meaning = "ทำให้เจ็บ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Eagerly", Meaning = "อย่างกระตือรือร้น", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Carelessly", Meaning = "อย่างไม่ระมัดระวัง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Proudly", Meaning = "อย่างภาคภูมิใจ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Shyly", Meaning = "อย่างอาย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Boldly", Meaning = "อย่างเป็นกล้า", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bed", Meaning = "เตียง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Clock", Meaning = "นาฬิกา", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Chair", Meaning = "เก้าอี้", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bag", Meaning = "กระเป๋า", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Notebook", Meaning = "สมุดโน้ต", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Since", Meaning = "ตั้งแต่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Before", Meaning = "ก่อน", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "After", Meaning = "หลังจาก", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Until", Meaning = "จนกระทั่ง", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "To", Meaning = "ไปยัง", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Into", Meaning = "เข้าไปใน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Out of", Meaning = "ออกจาก", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "At", Meaning = "ที่", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "On top of", Meaning = "บน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Paper", Meaning = "กระดาษ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bottle", Meaning = "ขวด", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Plate", Meaning = "จาน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cup", Meaning = "ถ้วย", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Spoon", Meaning = "ช้อน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fork", Meaning = "ส้อม", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Knife", Meaning = "มีด", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Room", Meaning = "ห้อง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Tablecloth", Meaning = "ผ้าคลุมโต๊ะ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Towel", Meaning = "ผ้าขนหนู", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Soap", Meaning = "สบู่", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Mirror", Meaning = "กระจก", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Toothbrush", Meaning = "แปรงสีฟัน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Toothpaste", Meaning = "ยาสีฟัน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sink", Meaning = "อ่างล้างหน้า", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sadly", Meaning = "อย่างเศร้า", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Nervously", Meaning = "อย่างเกรงใจ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bravely", Meaning = "อย่างกล้าหาญ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Calmly", Meaning = "อย่างสงบ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Quietly", Meaning = "อย่างเงียบ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Loudly", Meaning = "อย่างดัง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Floor", Meaning = "พื้น", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Ceiling", Meaning = "เพดาน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Wall", Meaning = "ผนัง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Light", Meaning = "แสง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bedroom", Meaning = "ห้องนอน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bathroom", Meaning = "ห้องน้ำ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Leave", Meaning = "ออกไป", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Enter", Meaning = "เข้า", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Exit", Meaning = "ออก", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Win", Meaning = "ชนะ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Lose", Meaning = "แพ้", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Start", Meaning = "เริ่ม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Finish", Meaning = "จบ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Like", Meaning = "ชอบ", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Love", Meaning = "รัก", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hate", Meaning = "เกลียด", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Along", Meaning = "ตาม", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Against", Meaning = "ต่อ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Inside", Meaning = "ภายใน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Outside", Meaning = "ภายนอก", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Amidst", Meaning = "ในขณะที่", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Living room", Meaning = "ห้องนั่งเล่น", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Kitchen", Meaning = "ห้องครัว", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Dining room", Meaning = "ห้องอาหาร", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Window", Meaning = "หน้าต่าง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Door", Meaning = "ประตู", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Street", Meaning = "ถนน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "City", Meaning = "เมือง", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Country", Meaning = "ประเทศ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "World", Meaning = "โลก", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "School", Meaning = "โรงเรียน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Clean", Meaning = "สะอาด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Dirty", Meaning = "สกปรก", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Healthy", Meaning = "มีสุขภาพดี", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sick", Meaning = "ป่วย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Heavy", Meaning = "หนัก", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Light", Meaning = "เบา", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Clearly", Meaning = "อย่างชัดเจน", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "As", Meaning = "เมื่อ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Even though", Meaning = "แม้ว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Once", Meaning = "เมื่อหนึ่งครั้ง", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Unless", Meaning = "นอกเหนือจาก", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Provided that", Meaning = "ให้", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Now that", Meaning = "ตอนนี้ที่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "In case", Meaning = "ในกรณีที่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Confidently", Meaning = "อย่างมั่นใจ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Naturally", Meaning = "อย่างเป็นธรรมชาติ", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Unusually", Meaning = "อย่างไม่ธรรมดา", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Certainly", Meaning = "อย่างแน่นอน", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Probably", Meaning = "อย่างน่าจะเป็น", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hard", Meaning = "ยาก", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Easy", Meaning = "ง่าย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Busy", Meaning = "คับขัน", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Free", Meaning = "ว่าง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "University", Meaning = "มหาวิทยาลัย", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hospital", Meaning = "โรงพยาบาล", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Supermarket", Meaning = "ซุปเปอร์มาร์เก็ต", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bank", Meaning = "ธนาคาร", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Park", Meaning = "สวนสาธารณะ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Beach", Meaning = "ชายหาด", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Mountain", Meaning = "ภูเขา", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Beside", Meaning = "ข้าง", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "In front of", Meaning = "ข้างหน้า", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Next to", Meaning = "ข้างๆ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Near", Meaning = "ใกล้", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Far", Meaning = "ไกล", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Between", Meaning = "ระหว่าง", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Heal", Meaning = "รักษา", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Teach", Meaning = "สอน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Learn", Meaning = "เรียนรู้", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Create", Meaning = "สร้าง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Destroy", Meaning = "ทำลาย", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Free", Meaning = "ว่าง", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Delicious", Meaning = "อร่อย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Disgusting", Meaning = "น่ารังเกียจ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sweet", Meaning = "หวาน", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sour", Meaning = "เปรี้ยว", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Spicy", Meaning = "เผ็ด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Though", Meaning = "แม้ว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whereas", Meaning = "ในขณะที่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "So that", Meaning = "เพื่อที่", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "In order to", Meaning = "เพื่อ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whether", Meaning = "ไม่ว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whenever", Meaning = "เมื่อไรก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Wherever", Meaning = "ที่ไหนก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bland", Meaning = "น่าเบื่อ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fix", Meaning = "ซ่อม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Break", Meaning = "แตก", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Build", Meaning = "ก่อสร้าง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Destroy", Meaning = "ทำลาย", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fix", Meaning = "ซ่อม", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "In", Meaning = "ใน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "On", Meaning = "บน", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Under", Meaning = "ใต้", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Above", Meaning = "เหนือ", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Below", Meaning = "ข้างล่าง", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Behind", Meaning = "ข้างหลัง", Type = "Prep", Level = "A"},
                new WordlistProvidedModel(){ Word = "Break", Meaning = "แตก", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Build", Meaning = "ก่อสร้าง", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Change", Meaning = "เปลี่ยน", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Stay", Meaning = "อยู่", Type = "Verb", Level = "A"},
                new WordlistProvidedModel(){ Word = "Delicious", Meaning = "อร่อย", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Disgusting", Meaning = "น่ารังเกียจ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sweet", Meaning = "หวาน", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sour", Meaning = "เปรี้ยว", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Spicy", Meaning = "เผ็ด", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Bland", Meaning = "น่าเบื่อ", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Busy", Meaning = "คับขัน", Type = "Adj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Quickly", Meaning = "อย่างรวดเร็ว", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Slowly", Meaning = "อย่างช้า", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Carefully", Meaning = "อย่างระมัดระวัง", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Easily", Meaning = "อย่างง่ายดาย", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "Hardly", Meaning = "เกือบจะไม่", Type = "Adv", Level = "A"},
                new WordlistProvidedModel(){ Word = "However", Meaning = "อย่างไรก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whatever", Meaning = "อะไรก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whichever", Meaning = "อะไรก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whoever", Meaning = "ใครก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Whomever", Meaning = "ใครก็ตาม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Providing", Meaning = "หาก", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sun", Meaning = "พระอาทิตย์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Moon", Meaning = "จันทร์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Star", Meaning = "ดาว", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sky", Meaning = "ท้องฟ้า", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cloud", Meaning = "เมฆ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Rain", Meaning = "ฝน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Snow", Meaning = "หิมะ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Wind", Meaning = "ลม", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fire", Meaning = "ไฟ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Earth", Meaning = "โลก", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Why", Meaning = "ทำไม", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "As if", Meaning = "เหมือนว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "As though", Meaning = "เหมือนว่า", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Insofar as", Meaning = "ในขอบเขตของ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Inasmuch as", Meaning = "ในขอบเขตของ", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Lest", Meaning = "เพื่อไม่ให้", Type = "Conj", Level = "A"},
                new WordlistProvidedModel(){ Word = "Moon", Meaning = "จันทร์", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Star", Meaning = "ดาว", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Sky", Meaning = "ท้องฟ้า", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Cloud", Meaning = "เมฆ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Rain", Meaning = "ฝน", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Snow", Meaning = "หิมะ", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Wind", Meaning = "ลม", Type = "Noun", Level = "A"},
                new WordlistProvidedModel(){ Word = "Fire", Meaning = "ไฟ", Type = "Noun", Level = "A"}

            };
        }
    }
}

